//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public Nullable<int> Seat { get; set; }
        public Nullable<int> Showtime { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PaymentTime { get; set; }
    
        public virtual Seat Seat1 { get; set; }
        public virtual Showtime Showtime1 { get; set; }
    }
}
